# need to be a bit less strict - nobody's perfect!
Metrics/AbcSize:
  Max: 25
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 25
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/WhileUntilDo:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3.0
  Exclude:
    - 'Gemfile'
    - 'spec/spec_helper.rb'
