#!/usr/bin/env ruby

require_relative 'src/colour_string.rb'
require_relative 'src/tokenizer/lexer.rb'
require_relative 'src/tokenizer/reader.rb'
require_relative 'src/util/logger.rb'
require_relative 'src/util/options.rb'

options = Util::Options.parse_arguments

Util::Logger.setup options

reader = Tokenizer::Reader.new options
lexer  = Tokenizer::Lexer.new reader, options

# TODO: send tokens to transpiler... also find a better name for transpiler

tokens = []
loop do
  token = lexer.next_token
  break if token.nil?
  tokens << token
end

if options[:tokens]
  tokens.each { |t| puts t.type.to_s.blue + ' ' + t.content.to_s }
  exit
end
