CallStackTooDeep:        Call stack too deep (exceeds %s). Infinite recursion?
CustomError:             "%s"
DivisionByZero:          Division by zero. (C'mon, really?)
ExperimentalFeature:     Experimental Feature (%s). If you're seeing this error, something has gone terribly wrong.
InvalidStringProperty:   Invalid string property (%s).
InvalidType:             Invalid type. Expected %s; got %s.
MismatchedConcatenation: Cannot concatenate "%s" with "%s".
PropertyDoesNotExist:    Property does not exist (%s).
VariableDoesNotExist:    Variable does not exist (%s).
WrongNumberOfParameters: String format with wrong number of parameters. Got %s.
