CallStackTooDeep:        Call stack too deep (exceeds %s). Infinite recursion?
CustomError:             "%s"
DivisionByZero:          Division by zero. (C'mon, really?)
InvalidType:             Invalid type. Expected %s; got %s.
ExperimentalFeature:     Experimental Feature (%s). If you're seeing this error, something has gone terribly wrong.
MismatchedConcatenation: Cannot concatenate "%s" with "%s".
