variables:
  - 大きさ
  - おおきさ
  - 長さ
  - ながさ
  - 数
  - かず
functions:
  # loop
  - 繰り返す
  - 繰りかえす
  - くり返す
  - くりかえす
  # return
  - 返す
  - かえす
  - なる
  - 戻る
  - もどる
  - 返る
  - かえる
illegal:
  - \n
  - ￥ｎ
  - 【
  - 】
  - 〇
