variables:
  # length properties
  - 大きさ
  - おおきさ
  - 長さ
  - ながさ
  - 数
  - かず
  # key list
  - キー列
  # shortcut accessor properties
  - 先頭
  - 後尾
  - 先頭以外
  - 後尾以外
  # empty comparison
  - 空
  - から
functions:
  # loop
  - 繰り返す
  - 繰りかえす
  - くり返す
  - くりかえす
  # return
  - 返す
  - かえす
  - なる
  - 戻る
  - もどる
  - 返る
  - かえる
  # misc
  - する
illegal:
  - ￥ｎ
  - 【
  - 】
  - 〇
