variables:
  # empty comparison
  - 空
  - から
functions:
  # loop
  - 繰り返す
  - 繰りかえす
  - くり返す
  - くりかえす
  # return
  - 返す
  - かえす
  - なる
  - 戻る
  - もどる
  - 返る
  - かえる
  # misc
  - する
  # existence conditional
  - ある
illegal:
  - ￥ｎ
  - 【
  - 】
  - 〇
