AccessOfSelfAsAttribute:               Cannot access attribute with same name as property owner (%s).
AssignmentToValue:                     Cannot assign to a value (%s).
AttributeDoesNotExist:                 Attribute does not exist (%s).
ExperimentalFeature:                   This feature is not yet supported (%s).
FunctionDefAlreadyDeclared:            Function %s has already been declared.
FunctionDefAmbiguousConjugation:       Function %s has conjugations which conlict with previously declared function %s. Use ! or ！ after the function definition to override previous conjugations.
FunctionDefDuplicateParameters:        Duplicate parameters in function definition.
FunctionDefNonVerbName:                Function declaration does not look like a verb (%s).
FunctionDefPrimitiveParameters:        Cannot declare function using primitives for parameters.
FunctionDefReserved:                   Cannot declare function with reserved name (%s).
InvalidFunctionDefParameter:           Invalid function definition parameter (%s).
InvalidLoopParameter:                  Invalid loop parameter (%s).
InvalidLoopParameterParticle:          Invalid loop parameter particle (%s).
InvalidPropertyComparison:             'Invalid property comparison (near: %s %s).'
InvalidPropertyOwner:                  Invalid property owner (%s).
InvalidReturnParameterParticle:        Invalid return parameter particle (%s). Did you mean %s?
InvalidStringAttribute:                Invalid string attribute (%s).
MultipleAssignment:                    Assignment found within assignment (%s).
TrailingCharacters:                    Trailing characters after %s.
UnclosedBlockComment:                  Unclosed block comment.
UnclosedString:                        Unclosed string (%s).
UnexpectedComparison:                  Unexpected comparison. Did you forget もし?
UnexpectedElse:                        Unexpected else.
UnexpectedElseIf:                      Unexpected else-if.
UnexpectedEof:                         Unexpected EOF.
UnexpectedEol:                         Unexpected EOL.
UnexpectedFunctionCall:                Unexpected function call (%s).
UnexpectedFunctionDef:                 Unexpected function definition (%s).
UnexpectedIndent:                      Unexpected indent.
UnexpectedInput:                       Unexpected input (%s).
UnexpectedLoop:                        Unexpected loop.
UnexpectedReturn:                      Expected return (%s).
UnexpectedScope:                       Unexpected scope (expected %s got %s).
VariableDoesNotExist:                  Variable does not exist (%s).
VariableNameAlreadyDelcaredAsFunction: Cannot declare variable with name already declared as function (%s).
VariableNameReserved:                  Cannot declare variable with reserved name (%s).
