AccessOfSelfAsProperty:                Cannot access property with same name as property owner (%s).
AssignmentToReadOnlyProperty:          Cannot assign to read-only property (%s).
AssignmentToValue:                     Cannot assign to a value (%s).
PropertyDoesNotExist:                  Property does not exist (%s).
EmptyOrUnclosedInterpolation:          Empty or unclosed string interpolation (%s).
ExperimentalFeature:                   This feature is not yet supported (%s).
FunctionDefAlreadyDeclared:            Function %s has already been declared.
FunctionDefAmbiguousConjugation:       Function %s has conjugations which conlict with previously declared function %s. Use ! or ！ after the function definition to override previous conjugations.
FunctionDefDuplicateParameters:        Duplicate parameters in function definition.
FunctionDefNonVerbName:                Function declaration does not look like a verb (%s).
FunctionDefPrimitiveParameters:        Cannot declare function using primitives for parameters.
FunctionDefReserved:                   Cannot declare function with reserved name (%s).
FunctionNameAlreadyDelcaredAsVariable: Cannot declare function with name already declared as variable (%s).
InvalidLoopParameter:                  Invalid loop parameter (%s).
InvalidLoopParameterParticle:          Invalid loop parameter particle (%s).
InvalidPropertyOwner:                  Invalid property owner (%s).
InvalidReturnParameterParticle:        Invalid return parameter particle (%s). Did you mean %s?
InvalidStringProperty:                 Invalid string property (%s).
InvalidSubstitution:                   Invalid substitution (%s). The value must be a variable or property.
MalformedString:                       Malformed string (%s).
UnclosedBlockComment:                  Unclosed block comment.
UnclosedString:                        Unclosed string (%s).
UnexpectedElse:                        Unexpected else.
UnexpectedElseIf:                      Unexpected else-if.
UnexpectedEof:                         Unexpected EOF.
UnexpectedFunctionDef:                 Unexpected function definition (%s).
UnexpectedIndent:                      Unexpected indent. Expected %s; got %s.
UnexpectedInput:                       Unexpected input (%s).
# TODO: (v1.1.0)
# UnexpectedLoop:                        Unexpected loop.
UnexpectedLineBreak:                   Unexpected line break (\).
UnexpectedQuestion:                    Unexpected question after %s.
UnexpectedReturn:                      Expected return (%s).
UnexpectedScope:                       Unexpected scope. Expected %s; got %s.
VariableDoesNotExist:                  Variable does not exist (%s).
VariableNameAlreadyDelcaredAsFunction: Cannot declare variable with name already declared as function (%s).
VariableNameReserved:                  Cannot declare variable with reserved name (%s).
VariableNameIllegalCharacters:         Cannot declare variable with name containing illegal characters (%s).
