inherit_from: ../.rubocop.yml

Layout/ExtraSpacing:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
